/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package view;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Aspire5
 */
public class detailKesmas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(detailKesmas.class.getName());
    private String idPengaduan;
    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form detailKesmas
     */
public detailKesmas(Frame parent, boolean modal) {
    super(parent, modal);
    initComponents(); // ✅ UI dulu
        cancelButton.setVisible(false);
        cancelButton.setEnabled(false);
        cancelButton.setFocusable(false);

    loadDetail(idPengaduan); // ✅ baru ambil data
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    public void loadDetail(String idPengaduan) {
        this.idPengaduan = idPengaduan;
        try {
            Object[] data = controller.PengaduanController.getDetailKesmasById(idPengaduan);

            if (data != null) {
                namaMasyarakat.setText(data[1] != null ? data[1].toString() : "-");
                Rt.setText(data[2] != null ? data[2].toString() : "-");

                String penyakit = data[3] != null ? data[3].toString() : "-";
                namaPenyakit.setText(penyakit);

                tanggalPengaduan.setText(data[4] != null ? data[4].toString() : "-");

                String statusHealth = penyakit.equals("-") ? "Sehat" : "Sakit";
                statusKesehatan.setText(statusHealth);

                if (statusHealth.equals("Sehat")) {
                    statusKesehatan.setForeground(new java.awt.Color(0, 153, 0));
                } else {
                    statusKesehatan.setForeground(java.awt.Color.RED);
                }

                statusPemeriksaan.setText(data[5] != null ? data[5].toString() : "Belum Diperiksa");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "Gagal memuat detail: " + e.getMessage(),
                    "Kesalahan",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaMasyarakat = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        Rt = new javax.swing.JLabel();
        namaPenyakit = new javax.swing.JLabel();
        tanggalPengaduan = new javax.swing.JLabel();
        statusKesehatan = new javax.swing.JLabel();
        statusPemeriksaan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaMasyarakat.setText("jLabel2");
        getContentPane().add(namaMasyarakat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));
        getRootPane().setDefaultButton(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        Rt.setText("jLabel3");
        getContentPane().add(Rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        namaPenyakit.setText("jLabel4");
        getContentPane().add(namaPenyakit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        tanggalPengaduan.setText("jLabel5");
        getContentPane().add(tanggalPengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        statusKesehatan.setText("jLabel6");
        getContentPane().add(statusKesehatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        statusPemeriksaan.setText("jLabel7");
        getContentPane().add(statusPemeriksaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Detail Kesehatan (3).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                detailKesmas dialog = new detailKesmas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Rt;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel namaMasyarakat;
    private javax.swing.JLabel namaPenyakit;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel statusKesehatan;
    private javax.swing.JLabel statusPemeriksaan;
    private javax.swing.JLabel tanggalPengaduan;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;



}
