/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import com.formdev.flatlaf.themes.FlatMacLightLaf;


/**
 *
 * @author Aspire5
 */
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.*;
import java.util.List;
import model.entity.LoginSession;
import controller.PengaduanController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

public class homePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(homePage.class.getName());

    /**
     * Creates new form homePage
     */
public homePage() {
    initComponents();
    setResizable(false);
    setLocationRelativeTo(null);

    setupTableUI();
    loadData();
    jScrollPane2.setWheelScrollingEnabled(true);
jScrollPane1.setWheelScrollingEnabled(true);

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20); // smooth scroll
jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);

// Biarkan panel mengikuti ukuran isi-natural, jangan dipaksa tinggi gede
jPanel1.setPreferredSize(null);
jPanel1.revalidate();
jButton4.setBorderPainted(false);
jButton4.setFocusPainted(false);
jButton4.setContentAreaFilled(false);
jButton4.setOpaque(false);

jButton4.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        loadData(); // Re-load data
        JOptionPane.showMessageDialog(null, "Data telah diperbarui!");
    }
});


}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton2 = new view.iconButton("")
        ;
        jButton3 = new view.iconButton("");
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(802, 570));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(804, 882));

        jPanel1.setMinimumSize(new java.awt.Dimension(802, 882));
        jPanel1.setPreferredSize(new java.awt.Dimension(802, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 720, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pengkes-img.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 280, 370, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pengfas-img.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/material-symbols_logout-rounded.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homepage-user.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 802, 657));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void setupTableUI() {
    jTable1.setRowHeight(40);
    jTable1.setShowGrid(false);
    jTable1.setIntercellSpacing(new Dimension(0, 0));
    jTable1.setFillsViewportHeight(true);

    JTableHeader header = jTable1.getTableHeader();
    header.setPreferredSize(new Dimension(0, 45));
    header.setOpaque(true);
    header.setBackground(new Color(240, 240, 240)); 
    header.setForeground(new Color(50, 50, 50));
    header.setFont(new Font("Segoe UI", Font.BOLD, 12));
    
    // agar tombol tetap center
    DefaultTableCellRenderer center = new DefaultTableCellRenderer();
    center.setHorizontalAlignment(SwingConstants.CENTER);

    for (int i = 1; i < jTable1.getColumnCount() - 1; i++) {
        jTable1.getColumnModel().getColumn(i).setCellRenderer(center);
    }

    jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
}

private void loadData() {
    try {
        String wilayahRT = LoginSession.getWilayah();
        List<Object[]> data = PengaduanController.getPengaduanByWilayah(wilayahRT);

        DefaultTableModel model = new DefaultTableModel(
                new String[]{"ID", "No", "Nama Pelapor", "Tipe", "Status", "Detail"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 5;
            }
        };

        int no = 1;
        for (Object[] row : data) {
            model.addRow(new Object[]{
                row[0],
                no++,
                row[1],
                row[2],
                (row[3] == null ? "Belum Diproses" : row[3]),
                "Lihat"
            });
        }

        jTable1.setModel(model);

        setupTableUI();

        // Sembunyikan Kolom ID
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);

        // Lebar kolom sesuai model baru
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);  
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(180);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);

        // Button Action di kolom terakhir
        jTable1.getColumn("Detail").setCellRenderer(new view.ButtonRenderer("detail"));
        jTable1.getColumn("Detail").setCellEditor(new view.ButtonEditor(this, "detail"));

        jScrollPane1.setViewportView(jTable1);
        jTable1.revalidate();
        jTable1.repaint();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Gagal memuat data: " + e.getMessage(),
                "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }
}


public void showDetailFaskes(String idPengaduan) {
    java.awt.Window window = SwingUtilities.getWindowAncestor(this);
    java.awt.Frame parent = (window instanceof java.awt.Frame) ? (java.awt.Frame) window : null;

    if (idPengaduan == null || idPengaduan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID pengaduan tidak valid!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        detailFaskes detail = new detailFaskes(parent, true); // konstruktor lama
        detail.setLocationRelativeTo(window);
        // kirim id ke popup lewat method atau variable public
        if (detail instanceof detailFaskes) {
            detail.loadData(idPengaduan); // pastikan method ini ada di kelas detailFaskes
        }
        detail.setVisible(true);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal menampilkan detail faskes.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }
}

public void showDetailKesmas(String idPengaduan) {
    java.awt.Window window = SwingUtilities.getWindowAncestor(this);
    java.awt.Frame parent = (window instanceof java.awt.Frame) ? (java.awt.Frame) window : null;

    if (idPengaduan == null || idPengaduan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID pengaduan tidak valid!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        detailKesmas detail = new detailKesmas(parent, true); // konstruktor lama
        detail.setLocationRelativeTo(window);
        if (detail instanceof detailKesmas) {
            detail.loadDetail(idPengaduan); // method serupa di popup masyarakat
        }
        detail.setVisible(true);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal menampilkan detail masyarakat.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }
}


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                        pengaduanFasilitas pengfas = new pengaduanFasilitas();
        pengfas.show();
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                pengaduanKesehatan pengkes = new pengaduanKesehatan();
        pengkes.show();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    keluar dialog = new keluar((java.awt.Frame) getParent(), true);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);

    if (dialog.getReturnStatus() == keluar.RET_OK) {
        login Login = new login();
        Login.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatMacLightLaf());
        } catch (Exception ex) {
            System.err.println("Gagal menerapkan tema: " + ex.getMessage());
        }

        java.awt.EventQueue.invokeLater(() -> new homePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
