/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.*;
import java.awt.*;
import javax.swing.UIManager;
import model.entity.LoginSession;
import model.entity.admin;


/**
 *
 * @author Aspire5
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login1
     */
    public login() {

        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        jShowPassword.setVisible(false); // mata tertutup disembunyikan dulu
        jPasswordField1.setEchoChar('*');SwingUtilities.invokeLater(() -> {

});


    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new view.RoundedButton("Login")
        ;
        jUsername = new javax.swing.JTextField();
        jHidePassword = new javax.swing.JLabel();
        jShowPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/submit.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setVerifyInputWhenFocusTarget(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 290, 40));

        jUsername.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(jUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 228, 290, 40));

        jHidePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/weui_eyes-off-outlined.png"))); // NOI18N
        jHidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHidePasswordMouseClicked(evt);
            }
        });
        getContentPane().add(jHidePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 310, 25, 20));

        jShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/weui_eyes-on-outlined.png"))); // NOI18N
        jShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jShowPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(jShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 310, 25, 20));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 300, 290, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login-page-bg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 802, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String username = jUsername.getText();
    String password = new String(jPasswordField1.getPassword());

    controller.LoginController loginController = new controller.LoginController();
    controller.LoginController.LoginRole role = loginController.autentikasi(username, password);

switch (role) {
    case ADMIN -> {
        // Ambil data admin dari DAO
        model.dao.adminDao adminDao = new model.dao.adminDao();
        model.entity.admin adminLogin = adminDao.getAdminByUsername(username);

        if (adminLogin != null) {
            // Simpan wilayah ke sesi login
            LoginSession.setWilayah(adminLogin.getWilayah());
        }

        LoginBerhasil popup = new LoginBerhasil(this, true);
        popup.setLocationRelativeTo(this);
        popup.setVisible(true);
        new dashboard().setVisible(true);
        dispose();
    }

    case KETUA_RT -> {
        // Ambil data ketua RT dari DAO
        model.dao.ketuaRtDao rtDao = new model.dao.ketuaRtDao();
        model.entity.ketuaRt rtLogin = rtDao.getKetuaRTByUsername(username);

        if (rtLogin != null) {
            // Simpan wilayah atau alamat sesuai kebutuhan
            LoginSession.setWilayah(rtLogin.getAlamat());
        }

        LoginBerhasil popup = new LoginBerhasil(this, true);
        popup.setLocationRelativeTo(this);
        popup.setVisible(true);
        new homePage().setVisible(true);
        dispose();
    }

    default -> 
        JOptionPane.showMessageDialog(this, "Username atau password salah!", 
                                      "Login Gagal", JOptionPane.ERROR_MESSAGE);
}



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jHidePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHidePasswordMouseClicked
        jHidePassword.setVisible(false);
        jShowPassword.setVisible(true);
        jPasswordField1.setEchoChar((char) 0);
    }//GEN-LAST:event_jHidePasswordMouseClicked

    private void jShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jShowPasswordMouseClicked
        jHidePassword.setVisible(true);
        jShowPassword.setVisible(false);
        jPasswordField1.setEchoChar('*');
    }//GEN-LAST:event_jShowPasswordMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        UIManager.setLookAndFeel(new com.formdev.flatlaf.themes.FlatMacLightLaf());

        // 🧩 Samakan pengaturan visual dengan pengaduanKesehatan
        UIManager.put("TextComponent.arc", 12);
        UIManager.put("Button.arc", 12);
        UIManager.put("Component.focusWidth", 1);
        UIManager.put("Component.focusColor", new java.awt.Color(0, 120, 215));
        UIManager.put("ScrollBar.thumbArc", 999);
        UIManager.put("ScrollBar.track", java.awt.Color.WHITE);
        UIManager.put("ScrollBar.thumb", new java.awt.Color(210, 210, 210));

        // 🔧 Tambahan agar warna dan latar textfield sama
        UIManager.put("Panel.background", Color.WHITE);
        UIManager.put("TextField.background", Color.WHITE);
        UIManager.put("PasswordField.background", Color.WHITE);
        UIManager.put("TextField.foreground", Color.BLACK);
        UIManager.put("PasswordField.foreground", Color.BLACK);


    } catch (Exception ex) {
        System.err.println("Gagal menerapkan tema FlatLaf: " + ex.getMessage());
    }

        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jHidePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel jShowPassword;
    private javax.swing.JTextField jUsername;
    // End of variables declaration//GEN-END:variables
}
