/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Aspire5
 */
public class RUpdateFasKes extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RUpdateFasKes.class.getName());
    private String idPengaduan;
    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form RUpdateFasKes
     */
    public RUpdateFasKes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jenisFasilitas = new javax.swing.JLabel();
        tanggalPengaduan = new javax.swing.JLabel();
        Rt = new javax.swing.JLabel();
        statusPemeriksaan = new javax.swing.JComboBox<>();
        namaKetuaRt = new javax.swing.JLabel();
        deskripsiKeluhan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update-submit.png"))); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));
        getRootPane().setDefaultButton(okButton);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Batal.png"))); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));
        getContentPane().add(jenisFasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 210, 20));
        getContentPane().add(tanggalPengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 210, 20));
        getContentPane().add(Rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 210, 20));

        statusPemeriksaan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(statusPemeriksaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 210, 20));
        getContentPane().add(namaKetuaRt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 65, 210, 20));

        deskripsiKeluhan.setText("jLabel6");
        getContentPane().add(deskripsiKeluhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Detail Fasilitas- db.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
public void loadDetail(String idPengaduan) {
    this.idPengaduan = idPengaduan; // ✅ simpan id untuk update

    try {
        Object[] data = controller.PengaduanController.getDetailFaskesById(idPengaduan);

        if (data != null) {
            namaKetuaRt.setText(data[1] != null ? data[1].toString() : "-");

            String ketuaRt = data[5] != null ? data[5].toString() : "-";
            String noRt = data[6] != null ? data[6].toString() : "-";

            namaKetuaRt.setText(ketuaRt);
            Rt.setText("RT " + (noRt.length() == 1 ? "0" + noRt : noRt));


            jenisFasilitas.setText(data[2] != null ? data[2].toString() : "-");

            deskripsiKeluhan.setText("<html>" +
                    (data[3] != null ? data[3].toString() : "-") +
                    "</html>");

            tanggalPengaduan.setText(data[6] != null ? data[6].toString() : "-");

            // ✅ Status dropdown
            statusPemeriksaan.removeAllItems();
            statusPemeriksaan.addItem("Belum Diproses");
            statusPemeriksaan.addItem("Sedang Diproses");
            statusPemeriksaan.addItem("Selesai");

            String statusDb = (data[5] != null) ? data[5].toString() : "Belum Diproses";

            statusDb = switch (statusDb.toLowerCase()) {
                case "sedang diproses" -> "Sedang Diproses";
                case "selesai" -> "Selesai";
                default -> "Belum Diproses";
            };

            statusPemeriksaan.setSelectedItem(statusDb);
        }

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,
                "Gagal memuat detail: " + e.getMessage(),
                "Kesalahan", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}



    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
            String statusBaru = statusPemeriksaan.getSelectedItem().toString();

    boolean success = controller.PengaduanController.updateStatusFaskes(idPengaduan, statusBaru);

    this.setVisible(false); // ✅ tutup popup detail dulu

    if(success) {
        new updateBerhasil((java.awt.Frame) getParent(), true).setVisible(true);
        doClose(RET_OK);
    } else {
        new updateGagal((java.awt.Frame) getParent(), true).setVisible(true);
        doClose(RET_CANCEL);
    }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RUpdateFasKes dialog = new RUpdateFasKes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Rt;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel deskripsiKeluhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jenisFasilitas;
    private javax.swing.JLabel namaKetuaRt;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox<String> statusPemeriksaan;
    private javax.swing.JLabel tanggalPengaduan;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
