/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Aspire5
 */
public class RUpdateKesmas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RUpdateKesmas.class.getName());

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form RUpdateKesmas
     */
    public RUpdateKesmas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }
    
private String idPengaduan; 

public void loadDetail(String idPengaduan) {
    this.idPengaduan = idPengaduan;
    try {
        Object[] data = controller.PengaduanController.getDetailKesmasById(idPengaduan);

        if (data != null) {

            namaMasyarakat.setText(data[1] != null ? data[1].toString() : "-");

            String noRt = data[2] != null ? data[2].toString() : "-";
            Rt.setText(noRt);

            String penyakit = data[3] != null ? data[3].toString() : "-";
            namaPenyakit.setText(penyakit);

            tanggalPengaduan.setText(data[4] != null ? data[4].toString() : "-");

            // ✅ Status kesehatan otomatis berdasarkan ada/tidaknya penyakit
            String statusHealth = penyakit.equals("-") ? "Sehat" : "Sakit";
            statusKesehatan.setText(statusHealth);

            // ✅ warna visual (opsional)
            if (statusHealth.equals("Sehat")) {
                statusKesehatan.setForeground(new java.awt.Color(0, 153, 0)); // hijau
            } else {
                statusKesehatan.setForeground(java.awt.Color.RED); // merah
            }

            // ✅ Status pemeriksaan: dropdown
            String statusDb = (data[5] != null) ? data[5].toString() : "Belum Diperiksa";
            jComboBox1.removeAllItems();
            jComboBox1.addItem("Belum Diperiksa");
            jComboBox1.addItem("Telah Diperiksa");
            jComboBox1.setSelectedItem(statusDb);
        }

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Gagal memuat detail: " + e.getMessage(),
                "Kesalahan",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
}





    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        namaPenyakit = new javax.swing.JLabel();
        statusKesehatan = new javax.swing.JLabel();
        tanggalPengaduan = new javax.swing.JLabel();
        Rt = new javax.swing.JLabel();
        namaMasyarakat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update-submit.png"))); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));
        getRootPane().setDefaultButton(okButton);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Batal.png"))); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        namaPenyakit.setText("jLabel6");
        getContentPane().add(namaPenyakit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        statusKesehatan.setText("jLabel5");
        getContentPane().add(statusKesehatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        tanggalPengaduan.setText("jLabel4");
        getContentPane().add(tanggalPengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        Rt.setText("jLabel3");
        getContentPane().add(Rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        namaMasyarakat.setText("namaMasyara");
        getContentPane().add(namaMasyarakat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Detail Kesehatan (3).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String statusBaru = jComboBox1.getSelectedItem().toString();
        boolean success = controller.PengaduanController.updateStatusKesmas(idPengaduan, statusBaru);

        this.setVisible(false); // sembunyikan popup detail dulu

        if(success) {
            new updateBerhasil((java.awt.Frame) getParent(), true).setVisible(true);
            doClose(RET_OK);
        } else {
            new updateGagal((java.awt.Frame) getParent(), true).setVisible(true);
            doClose(RET_CANCEL);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RUpdateKesmas dialog = new RUpdateKesmas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Rt;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel namaMasyarakat;
    private javax.swing.JLabel namaPenyakit;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel statusKesehatan;
    private javax.swing.JLabel tanggalPengaduan;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
