/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.PengaduanController;
import controller.PengaduanFaskesController;
import java.awt.Color;
import java.awt.Insets;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import raven.datetime.DatePicker;

/**
 *
 * @author Aspire5
 */
public class pengaduanFasilitas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(pengaduanFasilitas.class.getName());
    private DatePicker datePicker;
    private PengaduanController controller;
    /**
     * Creates new form pengaduanFasilitas
     */
    public pengaduanFasilitas() {
        initComponents();
        cbJenisFaskes.putClientProperty("FlatLaf.style", "arrowColor: #505050; focusColor: #C0C0C0");
        
        controller = new PengaduanController();

        setResizable(false);
        setLocationRelativeTo(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16); // smooth scroll
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE); 
        jPanel1.setBackground(java.awt.Color.WHITE);
        
        datePicker = new DatePicker();
        datePicker.setDateSelectionMode(DatePicker.DateSelectionMode.SINGLE_DATE_SELECTED);
        datePicker.setUsePanelOption(false);



        
     

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        cbJenisFaskes = new javax.swing.JComboBox<>();
        txtKeluhan = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 =  new view.RoundedButton("Kirim");
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(802, 570));
        setMinimumSize(new java.awt.Dimension(802, 570));
        setPreferredSize(new java.awt.Dimension(802, 570));

        jPanel1.setPreferredSize(new java.awt.Dimension(802, 820));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbJenisFaskes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rumah Sakit", "Klinik", "Puskesmas", "Posyandu" }));
        cbJenisFaskes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisFaskesActionPerformed(evt);
            }
        });
        jPanel1.add(cbJenisFaskes, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 295, 592, 39));
        jPanel1.add(txtKeluhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 375, 592, 40));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dokter", "Perawat", "Bidan" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 450, 592, 39));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kirim-sumit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 592, 47));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Batal.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 40, 18));
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(false);
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg_pengfas.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 802, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbJenisFaskesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisFaskesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisFaskesActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        homePage home = new homePage();
        home.show();
        dispose();// TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    PengaduanFaskesController controller = new PengaduanFaskesController();

    String jenisFaskes = cbJenisFaskes.getSelectedItem().toString();
    String keluhan = txtKeluhan.getText().trim();
    String tenagaMedis = jComboBox2.getSelectedItem().toString();

    if (jenisFaskes.isEmpty() || keluhan.isEmpty() || tenagaMedis.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Semua data harus diisi!",
                "Validasi",
                JOptionPane.WARNING_MESSAGE);
        return;
}

    LocalDate tanggalPengaduan = LocalDate.now();

    boolean success = controller.insertPengaduanFaskes(
            jenisFaskes,
            keluhan,
            tenagaMedis,
            tanggalPengaduan
    );

    if (success) {
        new kirim_berhasil(null, true).setVisible(true);
        resetForm();
    } else {
        JOptionPane.showMessageDialog(this,
                "Gagal mengirim pengaduan!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton1ActionPerformed

private void resetForm() {
    cbJenisFaskes.setSelectedIndex(0);
    txtKeluhan.setText("");
    jComboBox2.setSelectedIndex(0);
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
try {
    // Terapkan tema modern sebelum GUI dibuat
    UIManager.setLookAndFeel(new com.formdev.flatlaf.themes.FlatMacLightLaf());

        // Opsi tambahan (rounded, smooth, warna halus)
    UIManager.put("TextComponent.arc", 12);
    UIManager.put("Button.arc", 12);
    UIManager.put("Component.focusWidth", 1);
    UIManager.put("Component.focusColor", new java.awt.Color(0, 120, 215));
    UIManager.put("ScrollBar.thumbArc", 999);
    UIManager.put("ScrollBar.track", java.awt.Color.WHITE);
    UIManager.put("ScrollBar.thumb", new java.awt.Color(210, 210, 210));
    
//    j combo box
    UIManager.put("Component.arc", 12);
    UIManager.put("Button.arc", 12);
    UIManager.put("TextComponent.arc", 12);
    UIManager.put("Component.focusWidth", 1);
    UIManager.put("Component.focusColor", new Color(0, 120, 215));

    // 🌈 Scroll
    UIManager.put("ScrollBar.thumbArc", 999);
    UIManager.put("ScrollBar.track", Color.WHITE);
    UIManager.put("ScrollBar.thumb", new Color(210, 210, 210));

    // 🎨 ComboBox Flat Style
    UIManager.put("ComboBox.arc", 12); // sudut rounded
    UIManager.put("ComboBox.borderColor", new Color(200, 200, 200)); 
    UIManager.put("ComboBox.selectionBackground", new Color(0, 120, 215)); 
    UIManager.put("ComboBox.selectionForeground", Color.WHITE);
    UIManager.put("ComboBox.buttonBackground", Color.WHITE);
    UIManager.put("ComboBox.buttonHoverBackground", new Color(240, 240, 240));
    UIManager.put("ComboBox.padding", new Insets(5, 10, 5, 10));
    UIManager.put("ComboBox.focusedBackground", Color.WHITE);
    UIManager.put("ComboBox.minimumWidth", 150);
    
    UIManager.put("ComboBox.buttonArrowColor", new Color(90, 90, 90)); // warna default
    UIManager.put("ComboBox.buttonHoverArrowColor", new Color(0, 120, 215)); // hover
    UIManager.put("ComboBox.buttonArrowType", "chevron"); // gaya panah

} catch (Exception ex) {
    System.err.println("Gagal menerapkan tema FlatLaf: " + ex.getMessage());
}
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new pengaduanFasilitas().setVisible(true));
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbJenisFaskes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtKeluhan;
    // End of variables declaration//GEN-END:variables
}
