/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import controller.KetuaRtController;
import javax.swing.JOptionPane;
import model.entity.ketuaRt;
import controller.*;
import java.util.UUID;


/**
 *
 * @author Aspire5
 */
public class tambahAkunDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tambahAkunDialog.class.getName());

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form tambahAKunDialog
     */
    public tambahAkunDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
                jShowPassword.setVisible(false); // mata tertutup disembunyikan dulu
        jPasswordField1.setEchoChar('*');
        SwingUtilities.invokeLater(() -> {
        });

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHidePassword = new javax.swing.JLabel();
        jShowPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jHidePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/weui_eyes-off-outlined.png"))); // NOI18N
        jHidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHidePasswordMouseClicked(evt);
            }
        });
        getContentPane().add(jHidePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 183, -1, -1));

        jShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/weui_eyes-on-outlined.png"))); // NOI18N
        jShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jShowPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(jShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 183, -1, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 200, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 200, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 115, 200, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 85, 200, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 200, -1));

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tambah_sumbit_btn.png"))); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 220, -1, -1));
        getRootPane().setDefaultButton(okButton);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Batal.png"))); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tambah_akun_bg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    try {
        // Ambil data dari form
        String nama = jTextField1.getText().trim();
        String username = jTextField4.getText().trim();
        String password = new String(jPasswordField1.getPassword()).trim();
        String rtRwText = jTextField2.getText().trim(); // format: "05,02" atau "05"
        String alamat = jTextField3.getText().trim();

        // ==== VALIDASI UMUM ====
        if (nama.isEmpty() || username.isEmpty() || password.isEmpty() || rtRwText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Semua kolom wajib diisi, kecuali RW (boleh kosong).",
                "Validasi", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ==== VALIDASI USERNAME ====
        if (!username.matches("^[a-zA-Z0-9_]+$")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Username hanya boleh mengandung huruf, angka, dan underscore (_).",
                "Format Tidak Valid", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ==== VALIDASI PASSWORD ====
        if (password.length() < 5) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Password minimal 5 karakter.",
                "Format Tidak Valid", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

                // ==== VALIDASI RT & RW ====
         String rawRT_RW = rtRwText.trim();

        // Split berdasarkan slash (RT / RW)
        String[] parts = rawRT_RW.split("/");

        // ---- VALIDASI RT ----
        String rawRt = parts[0].trim();
        String noRt = rawRt.replaceAll("[^0-9]", ""); // hanya ambil angka

        if (noRt.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Nomor RT wajib diisi dan harus berupa angka.",
                "Format Tidak Valid", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ---- VALIDASI RW (opsional) ----
        String rw = null;
        ketuaRt data = new ketuaRt();
        if (parts.length > 1) {
            String rawRw = parts[1].trim();
            rw = rawRw.replaceAll("[^0-9]", "");

            if (!rw.isEmpty() && !rw.matches("\\d+")) {
                JOptionPane.showMessageDialog(this,
                    "Nomor RW harus berupa angka jika diisi.",
                    "Format Tidak Valid", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        

        // RW boleh kosong → set null
        data.setRw((rw != null && !rw.isEmpty()) ? rw : null);

        // Alamat boleh kosong
        data.setAlamat(jTextField3.getText().trim());

        // Debug print untuk memastikan benar
        System.out.println("ISI TEXTBOX RT/RW SEBENARNYA: " + rtRwText);
        System.out.println("RT = " + noRt);
        System.out.println("RW = " + (rw != null && !rw.isEmpty() ? rw : "(kosong)"));

        // Set ke entity (String sesuai DB)
        data.setNoRt(noRt);
        data.setRw((rw != null && !rw.isEmpty()) ? rw : null);

        // ==== VALIDASI NAMA ====
        if (!nama.matches("^[a-zA-Z\\s]+$")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Nama hanya boleh berisi huruf dan spasi.",
                "Format Tidak Valid", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ==== BUAT OBJEK ENTITY ====
        data.setNamaUsers(nama);
        data.setUsername(username);
        data.setPassword(password);
        data.setNoRt(noRt);
        data.setRw(rw);
        data.setAlamat(alamat);

        // ==== SIMPAN KE DATABASE ====
        boolean success = controller.KetuaRtController.tambah(data);


        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Akun berhasil ditambahkan.",
                "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Kosongkan field setelah berhasil
            jTextField1.setText("");
            jTextField2.setText("");
            jPasswordField1.setText("");
            jTextField3.setText("");
            jTextField4.setText("");

            doClose(RET_OK);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Gagal menambah akun.",
                "Kesalahan", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Terjadi kesalahan: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }


    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jHidePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHidePasswordMouseClicked
        jHidePassword.setVisible(false);
        jShowPassword.setVisible(true);
        jPasswordField1.setEchoChar((char) 0);
    }//GEN-LAST:event_jHidePasswordMouseClicked

    private void jShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jShowPasswordMouseClicked
        jHidePassword.setVisible(true);
        jShowPassword.setVisible(false);
        jPasswordField1.setEchoChar('*'); 
    }//GEN-LAST:event_jShowPasswordMouseClicked
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                tambahAkunDialog dialog = new tambahAkunDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jHidePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel jShowPassword;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
